# Generated by Django 4.2.1 on 2023-05-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options_historicalnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
